Imports System.Runtime.CompilerServices
Imports System.Text
Imports System.Threading.Tasks

Namespace FlowPreservation
	''' <summary>
	''' Provides a name for delegates generated by FlowPreservation infrastructure and checks for it
	''' </summary>
	Friend NotInheritable Class MethodNameHelper
		Private Shared ReadOnly defaultMethodName As String = "<" & GetType(MethodNameHelper).Namespace & ">lambda_method"
		Public Shared Function GetLambdaMethodName() As String
			Return defaultMethodName
		End Function

		Public Shared Function IsOurLambdaMethod(ByVal methodName As String) As Boolean
			Return defaultMethodName.Equals(methodName)
		End Function
	End Class
End Namespace
